# Site settings
baseurl: "/apps" # the subpath of your site, e.g. /blog/
url: "http://ajaymore.net" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: true
markdown: kramdown
permalink: /:title
relative_permalinks: true